### ISSUE TITLE
Run CleanTweets.py on Decahose, make sure that CleanTweets.py is functioning properly

### ISSUE THREAD

**Issue by pmhauck** [VT-ATD/Data_Proc#1]

**Comment by pmhauck** [comment]
We want to see 
1) CleanTweetsPy run once
2) an output of a Cleaned Twitter File

**Comment by sdbookhu** [comment]
I ran the CleanTweets.py on all the Decahose_files. All cleaned files are marked *prcsd. Also, you must have nltk, numpy, and stop words installed for this to function.
