### ISSUE TITLE
Apply vader to 1000 decahose tweets

### ISSUE THREAD

**Issue by pmhauck** [VT-ATD/Data_Proc#10]

**Comment by pmhauck** [comment]
We will know this is done when we have an output file, with each line like:

{
"body"="I am a real tweet!",
"neg"="someneg score",
...
"compound"="some compound score"
}

**Comment by sdbookhu** [comment]
Have applied VADER to the 1000 tweets and then wrote a new file with the polarity scores at the end of the tweet

Below is an example of each tweet in the 1000 lines

{"body": "@glen_ichinose what is this i need it", ...
"polarity_scores": {"neg": 0.0, "neu": 1.0, "pos": 0.0, "compound": 0.0}}
Took 1.5 hours
