### ISSUE TITLE
R script: Analyze Enriched Tweets

### ISSUE THREAD

**Issue by pmhauck** [VT-ATD/Data_Proc#11]

**Comment by pmhauck** [comment]
We will know this is done when we have an R script that:

1) takes in the enriched tweet file
2) outputs various visualizations, characterizations, etc. of each tweet

**Comment by sdbookhu** [comment]
I have gotten the tweets into an analyzable format. Took around 6ish hours. Mostly due to trying to figure out what format to put the tweets into.
